spring:
  datasource:
    # Notice the added allowPublicKeyRetrieval=true at the end of the URL
    url: jdbc:mysql://localhost:3306/wap_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123363
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Notice the dialect is now just MySQLDialect
        dialect: org.hibernate.dialect.MySQLDialect