spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wap_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123363
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  
  # Gmail SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: wap.ems.notifications@gmail.com
    password: ypxcumxblxdehslj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true